Update 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,27 +1,147 @@
 #!/usr/bin/env bash
 
-# Configure Nginx so that its HTTP response contains a custom header
+# duplicate web-01 to web-02
 
-# HTTP response contains a custom header (on web-01 and web-02)
+# these scripts are an upgrade from the web-server scripts...
 
-var=$(hostname)
+# uncomment to see the script run in action
 
-new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
+#set -x
 
-new_string2="server {\n\tadd_header X-Served-By $var;"
+# colors
 
-apt-get update -y
+blue='\e[1;34m'
 
-apt-get install nginx -y
+brown='\e[0;33m'
 
-echo "Hello World!" > /usr/share/nginx/html/index.html
+green='\e[1;32m'
 
-mkdir -p /var/www/html
+reset='\033[0m'
 
-echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
+echo -e "${blue}Updating and doing some minor checks...${reset}\n"
 
-sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
+function install() {
 
-sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
+	command -v "$1" &> /dev/null
 
-sudo service nginx start
+	#shellcheck disable=SC2181
+
+	if [ $? -ne 0 ]; then
+
+		echo -e "	Installing: ${brown}$1${reset}\n"
+
+		sudo apt-get update -y -qq && \
+
+			sudo apt-get install -y "$1" -qq
+
+		echo -e "\n"
+
+	else
+
+		echo -e "	${green}${1} is already installed.${reset}\n"
+
+	fi
+
+}
+
+install nginx #install nginx
+
+echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
+
+# allowing nginx on firewall
+
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+
+if [ -d "/var/www" ]; then
+
+	sudo chown -R "$USER":"$USER" /var/www
+
+	sudo chmod -R 755 /var/www
+
+else
+
+	sudo mkdir -p /var/www
+
+	sudo chown -R "$USER":"$USER" /var/www
+
+	sudo chmod -R 755 /var/www
+
+fi
+
+# create directories if not present
+
+for dir in /var/www/{html,error}; do
+
+	if ! [ -d "$dir" ]; then
+
+		mkdir -p "$dir"
+
+	fi
+
+done
+
+# creating new index
+
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+
+"server {
+
+		listen 80 default_server;
+
+		listen [::]:80 default_server;
+
+		root /var/www/html;
+
+		index index.html index.htm index.nginx-debian.html
+
+		server_name_;
+
+		add_header X-Served-By \$hostname;
+
+		location / {
+
+			try_files \$uri \$uri/ =404;
+
+		}
+
+		if (\$request_filename ~ redirect_me){
+
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+
+		}
+
+		error_page 404 /error_404.html;
+
+		location = /error_404.html {
+
+			internal;
+
+		}
+
+}"
+
+#shellcheck disable=SC2154
+
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+
+	sudo service nginx start
+
+else
+
+	sudo service nginx restart
+
+fi
